project:
  type: website
  output-dir: docs

website:
  title: "PSDV-C019"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog


format:
  html:
    theme:
      light: [cosmo, styles.scss]
    highlight-style: a11y-dark
    mainfont: "Roboto"
    code-copy: true
    code-overflow: wrap


execute:
  freeze: auto